Architecture docs
Azure/modern-web-app-pattern-java pull request #31
Opened 2024-10-23 16:04 UTC by nickdala

2024-10-23 16:20 UTC, adrianhall requested changes

2024-10-23 16:20 UTC, adrianhall commented on CHANGES.md
> +The reference sample in this repository builds on the previous [Reliable Web App Pattern for Java](https://aka.ms/eap/rwa/java). Whereas the Reliable Web App Pattern focused on re-platforming an exis
I think it is worthwhile saying something like "This was the requirement.  To achieve this requirement, we decided to <design discussion>.  This resulted in the following additional infrastructure".  Even though the text is great below it, the introduction is weak.

2024-10-23 16:20 UTC, adrianhall commented on README.md
> +This repository contains a collection of patterns and best practices for building modern Java web applications. The patterns are designed to be used with the [Spring Framework](https://spring.io/) an
I think adjusting the introduction here would work as well.  This repository provides a "real-world" application that implements the best practices and design patterns discussed in [article]; using <tech-stack>.  It can be easily adapted to other technology stacks and cloud providers"  - works better, I think.

2024-10-23 16:20 UTC, adrianhall commented on additional-resources.md
> +In this guide we provided the content to build a web app based on other resources such as the Azure Architecture Center. In this section we'll highlight those source materials that you can use to lea
As with the CHANGES, let's add a little description of the requirement and design changes that we implemented.

2024-10-23 16:20 UTC, adrianhall commented on prerequisites.md
> + If you want to use a VSCode DevContainer see the `VSCode DevContainer prerequisites` section below
Move this sentence to below the prerequisites.

2024-10-23 16:20 UTC, adrianhall commented on prerequisites.md
> +| Windows     |    ❌     |      ❌      |
Do we seriously not work on VSCode + DevContainer on Windows (no WSL)?  What is the problem with supporting it?

2024-10-24 18:42 UTC, KSchlobohm reviewed
looks good with suggestions from Adrian

2024-10-24 18:42 UTC, KSchlobohm commented on CHANGES.md
> +* **Azure Container Apps** - The Modern Web App Pattern reference sample uses Azure Container Apps to host a new email processing service that was separated from the web API as part of applying the [
```suggestion
* **Azure Container Apps** - The Modern Web App pattern reference sample uses Azure Container Apps to host a new email processing service that was separated from the web API as part of applying the [Strangler Fig pattern](https://learn.microsoft.com/azure/architecture/patterns/strangler-fig). Azure Container Apps is a fully managed serverless platform for running containerized apps. The reference sample uses Azure Container Apps because it provides managed container orchestration with support for automatic scale-in and scale-out based on a wide variety of rules using [KEDA](https://keda.sh/docs/2.13/) scalers. This allows the email processing service to automatically scale to zero when there is no work to be done and automatically scale up, as needed, based on the number of messages in the Service Bus queue.
```

2024-10-24 18:42 UTC, KSchlobohm commented on CHANGES.md
> +* **Azure Container Registry** - Because the Modern Web App Pattern reference sample uses Azure Container Apps, it also uses Azure Container Registry to store the container images for the email proce
```suggestion
* **Azure Container Registry** - Because the Modern Web App pattern reference sample uses Azure Container Apps, it also uses Azure Container Registry to store the container images for the email processing service. Azure Container Registry allows you to build, store, and manage container images and artifacts in a private registry for all types of container deployments. Azure Container Registry supports the reference sample's SLO goals by being highly available thanks to its [geo-replication](https://learn.microsoft.com/azure/container-registry/container-registry-geo-replication#configure-geo-replication) feature.
```

2024-10-24 18:42 UTC, KSchlobohm commented on CHANGES.md
> +* **Azure Service Bus** - The Modern Web App Pattern reference sample uses Azure Service Bus to enable message-based communication between the CAMS Application and the new email processing service. U
```suggestion
* **Azure Service Bus** - The Modern Web App pattern reference sample uses Azure Service Bus to enable message-based communication between the CAMS Application and the new email processing service. Using message-based communication allows improved reliability and performance by decoupling the CAMS application from the email processing service. Applying a [Queue-Based Load Leveling pattern](https://learn.microsoft.com/azure/architecture/patterns/queue-based-load-leveling) means that neither the CAMS application nor the email processing service will be affected by large numbers of email requests. The reference sample uses Azure Service Bus because it provides a fully managed, reliable, and secure messaging service that supports the reference sample's SLO goals.
```

2024-10-24 18:42 UTC, KSchlobohm commented on CHANGES.md
> +* **Azure App Configuration Feature Manager** - The Modern Web App Pattern uses Azure App Configuration to store the CAMS application settings. Azure App Configuration is a managed service that provi
```suggestion
* **Azure App Configuration Feature Manager** - The Modern Web App pattern uses Azure App Configuration to store the CAMS application settings. Azure App Configuration is a managed service that provides a central place to manage application settings and feature flags.
```

2024-10-24 18:42 UTC, KSchlobohm commented on README.md
> +This project has [a companion article in the Azure Architecture Center](TODO:) that describes design patterns and best practices. Here's an outline of the contents in this readme:
we should be able to use the aka link as an intermediary
```suggestion
This project has [a companion article in the Azure Architecture Center](https://aka.ms/eap/mwa/java/doc) that describes design patterns and best practices. Here's an outline of the contents in this readme:
```

2024-10-24 18:42 UTC, KSchlobohm commented on additional-resources.md
> +## Next Step
let's remove the next step link

2024-10-24 18:42 UTC, KSchlobohm commented on prerequisites.md
> +| Windows     |    ❌     |      ❌      |
Should this row be combined with the Windows WSL row? is the intent here to call out a difference between clone into windows file system vs a clone into windows WSL file system?

2024-10-24 18:42 UTC, KSchlobohm commented on prod-deployment.md
> +![TODO: Diagram showing the network focused architecture of the reference implementation.](./docs/assets/diagrams/modern-web-app-java.svg)
```suggestion
![Diagram showing the network focused architecture of the reference implementation.](./docs/assets/diagrams/modern-web-app-java.svg)
```

2024-10-25 16:42 UTC, KSchlobohm approved these changes
LGTM

2024-10-25 19:14 UTC, merged